(() => {
 const KEY='purple-encore-tour-v1';
 const stories=['Every great show starts here. Collect the sparks that bring your rehearsal room to life.','The city is your backdrop. Win over the rooftop crowd, one heart at a time.','Your first packed room. Gather the notes and get the whole club moving.','Open skies, bright lights. Collect tickets to bring the festival crowd together.','You made it to the main stage. Bring the hearts, fill the lights, and take your encore.'];
 const tips=['Swap neighboring pieces to match three. Only a successful match uses a move.','Match four to make an Encore piece. Match it again to clear its row.','Match five to make a Spotlight. Swap it with a color you want to collect.','The gap divides the board. Look for matches around both sides of the stage.','Combine two special pieces for a bigger clear. Save them for the right moment.'];
 let progress={stars:[0,0,0,0,0],best:[0,0,0,0,0],session:null},selectedStop=0,storageOK=true;
 try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&Array.isArray(s.stars)&&s.stars.length===5){progress.stars=s.stars.map(x=>Number.isInteger(x)?Math.min(3,Math.max(0,x)):0);progress.best=Array.from({length:5},(_,i)=>Math.max(0,Number(s.best?.[i])||0));progress.session=Number.isInteger(s.session?.level)&&s.session.level>=0&&s.session.level<5?s.session:null;}}catch{storageOK=false;}
 function persist(){try{localStorage.setItem(KEY,JSON.stringify(progress));}catch{storageOK=false;}$('saveNote').textContent=storageOK?'Your tour saves on this device.':'Progress stays in this session. Device storage is unavailable.';}
 function unlocked(n){return n===0||progress.stars[n-1]>0;}
 function next(){return Math.max(0,progress.stars.findIndex(x=>!x));}
 function route(){
  $('tourStars').textContent=progress.stars.reduce((a,b)=>a+b,0);
  $('tourRoute').replaceChildren();
  stages.forEach((s,i)=>{const button=document.createElement('button');button.className='tour-stop'+(progress.stars[i]?' complete':'')+(!unlocked(i)?' locked':'');button.disabled=!unlocked(i);button.innerHTML=`<span class="stop-number">${unlocked(i)?String(i+1).padStart(2,'0'):'⌑'}</span><span class="stop-name">${s.name}</span><span class="stop-stars" aria-label="${progress.stars[i]} of 3 stars">${'★'.repeat(progress.stars[i])}${'☆'.repeat(3-progress.stars[i])}</span>`;button.setAttribute('aria-label',`${s.name}, ${progress.stars[i]} of 3 stars${!unlocked(i)?', locked':''}`);button.onclick=()=>brief(i);$('tourRoute').appendChild(button);});
  const all=progress.stars.every(Boolean),resume=progress.session&&unlocked(progress.session.level);
  $('tourPlay').textContent=resume?'Resume your show →':all?'Replay the headline →':'Take the next stage →';
  $('tourStatus').textContent=resume?`${stages[progress.session.level].name} is waiting for your return.`:all?'Five venues. One unforgettable tour. Replay to improve your stars.':progress.stars.some(Boolean)?`${stages[next()].name} is unlocked. Your next crowd is waiting.`:'Every headline show starts with a first rehearsal.';
  $('tourPlay').onclick=()=>resume?resumeShow():brief(all?4:next());persist();
 }
 function showTour(){if(busy)return;saveSession();finished=true;$('playScreen').hidden=true;$('tour').hidden=false;document.body.dataset.screen='tour';route();$('tourPlay').focus();}
 function brief(n){if(!unlocked(n))return;selectedStop=n;$('briefNumber').textContent=`TOUR STOP ${String(n+1).padStart(2,'0')}`;$('briefTitle').textContent=stages[n].name;$('briefStory').textContent=stories[n];$('briefIcon').className='token token-'+stages[n].type;$('briefGoal').textContent=`Collect ${stages[n].target} ${['stars','hearts','notes','beats','tickets','gems'][stages[n].type]}`;$('briefMoves').textContent=`${stages[n].moves} moves · no timer`;$('briefTip').textContent=tips[n];$('briefing').showModal();}
 function enter(){ $('tour').hidden=true;$('playScreen').hidden=false;document.body.dataset.screen='play';document.body.dataset.venue=String(level);$('feedback').textContent=stories[level];updateStats();$('backTour').focus(); }
 function launch(n){start(n);enter();saveSession();}
 function saveSession(){if(finished||!board.length||busy)return;progress.session={level,board:board.map(t=>t?{...t}:null),moves,score,collected};persist();}
 function resumeShow(){const s=progress.session;const n=s?.level;if(!Number.isInteger(n)||n<0||n>=5||!unlocked(n)){progress.session=null;route();return;}start(n);const valid=Array.isArray(s.board)&&s.board.length===64&&s.board.every((t,i)=>activeCell(i)?t&&Number.isInteger(t.type)&&t.type>=0&&t.type<6&&[null,'row','color'].includes(t.special):t===null)&&Number.isInteger(s.moves)&&s.moves>0&&s.moves<=stages[n].moves&&Number.isInteger(s.collected)&&s.collected>=0&&s.collected<stages[n].target&&Number.isInteger(s.score)&&s.score>=0;
  if(valid){board=s.board.map(t=>t?{...t}:null);moves=s.moves;score=s.score;collected=s.collected;if(matches().length||!possible()){fresh();}render();}enter();saveSession();}
 function finish(won){progress.session=null;const earned=won?(moves>=Math.ceil(stages[level].moves*.4)?3:moves>=Math.ceil(stages[level].moves*.15)?2:1):0;if(won){progress.stars[level]=Math.max(progress.stars[level],earned);progress.best[level]=Math.max(progress.best[level],score);}persist();$('resultEyebrow').textContent=won?'THE CROWD IS YOURS':'ONE MORE TAKE';$('resultTitle').textContent=won?(level===4?'Your headline moment.':'You lit up the stage.'):'Your encore is waiting.';document.querySelector('.result-symbol').textContent=won?'★'.repeat(earned):'↻';$('resultText').textContent=won?`${score.toLocaleString()} points · ${earned} tour ${earned===1?'star':'stars'}. ${level===4?'The whole tour is complete. Replay venues to improve your stars.':stages[level+1].name+' is now unlocked.'}`:`You collected ${Math.min(collected,stages[level].target)} of ${stages[level].target}. Try using four-piece matches to clear more of the board.`;$('continue').textContent=won?(level===4?'See your tour →':'Next venue →'):'Try another take →';$('continue').onclick=()=>{$('result').close();if(won){showTour();if(level<4)brief(level+1);}else launch(level);};$('resultTour').onclick=()=>{$('result').close();showTour();};$('result').showModal();}
 window.concertTour={finish,saveSession,update(){const pct=Math.min(100,Math.round(collected/stages[level].target*100));$('energyValue').textContent=pct+'%';document.body.style.setProperty('--energy',pct/100);$('backTour').disabled=busy;}};
 $('beginShow').onclick=()=>{$('briefing').close();launch(selectedStop);};$('cancelBrief').onclick=()=>$('briefing').close();$('backTour').onclick=showTour;
 function $(id){return document.getElementById(id);}
 document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();if(!busy){$('result').close();$('briefing').close();showTour();}});
 $('restart').onclick=()=>{if(!busy){start(level);enter();saveSession();}};
 finished=true;$('playScreen').hidden=true;document.body.dataset.screen='tour';route();
})();
