(() => {
 const KEY='purple-encore-tour-v1';
 const stories=['Every great show starts here. Collect the sparks that bring your rehearsal room to life.','The city is your backdrop. Win over the rooftop crowd, one heart at a time.','Your first packed room. Gather the notes and get the whole club moving.','Open skies, bright lights. Collect tickets to bring the festival crowd together.','You made it to the main stage. Bring the hearts, fill the lights, and take your encore.','A new world, a new rhythm. Collect the beats for your moonlit soundcheck.','The neon skyline is listening. Gather gems to light the rooftop.','Midnight brings a new crowd. Collect notes and build your biggest combinations.','Aurora lights sweep the festival. Gather tickets around the divided stage.','One final galaxy-wide encore. Collect stars to bring the whole tour together.'];
 const tips=['Swap neighboring pieces to match three. Only a successful match uses a move.','Match four to make a laser. Its arrows show whether it clears a row or column.','Match five to make a Galaxy bomb. Swap it with a color you want to collect.','The gap divides the board. Look for matches around both sides of the stage.','Combine two special pieces for a bigger clear. Save them for the right moment.'];
 let progress={stars:Array(stages.length).fill(0),best:Array(stages.length).fill(0),session:null},selectedStop=0,storageOK=true,chapter=0,loadout=[];
 try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&Array.isArray(s.stars)&&s.stars.length>0){progress.stars=Array.from({length:stages.length},(_,i)=>Number.isInteger(s.stars[i])?Math.min(3,Math.max(0,s.stars[i])):0);progress.best=Array.from({length:stages.length},(_,i)=>Math.max(0,Number(s.best?.[i])||0));progress.session=Number.isInteger(s.session?.level)&&s.session.level>=0&&s.session.level<stages.length?s.session:null;}}catch{storageOK=false;}
 function persist(){try{localStorage.setItem(KEY,JSON.stringify(progress));}catch{storageOK=false;}$('saveNote').textContent=storageOK?'Your tour saves on this device.':'Progress stays in this session. Device storage is unavailable.';}
 function unlocked(n){return n===0||progress.stars[n-1]>0;}
 function next(){const n=progress.stars.findIndex(x=>!x);return n<0?stages.length-1:n;}
 function currentStop(){return progress.session&&unlocked(progress.session.level)?progress.session.level:next();}
 function centerCurrentStage(){const map=document.querySelector('.world-map'),pin=$('tourRoute').children[currentStop()%5];if(!map||!pin||$('tour').hidden||Math.floor(currentStop()/5)!==chapter)return;const x=pin.offsetLeft-map.clientWidth/2;map.scrollLeft=Math.min(Math.max(0,x),Math.max(0,map.scrollWidth-map.clientWidth));}
 function route(){
  $('worldLabel').textContent=chapter===0?'WORLD 01 · AFTERGLOW':'WORLD 02 · NIGHTWAVE';document.body.dataset.world=String(chapter);$('chapterPrev').disabled=chapter===0;$('chapterNext').disabled=chapter===Math.ceil(stages.length/5)-1;$('chapterName').textContent=chapter===0?'Afterglow · stages 1–5':'Nightwave · stages 6–10';$('tourStars').textContent=progress.stars.reduce((a,b)=>a+b,0);
  $('tourRoute').replaceChildren();
  stages.forEach((s,i)=>{if(Math.floor(i/5)!==chapter)return;const button=document.createElement('button');button.className='tour-stop'+(progress.stars[i]?' complete':'')+(!unlocked(i)?' locked':'');button.disabled=!unlocked(i);if(i===currentStop()){button.className+=' current'+(progress.session?.level===i?' in-progress':' next-stage');button.setAttribute('aria-current','step');}button.innerHTML=`<span class="stop-number">${unlocked(i)?String(i+1):'<svg class="node-lock" viewBox="0 0 24 24" aria-hidden="true"><path d="M7 10V7a5 5 0 0 1 10 0v3" fill="none" stroke="currentColor" stroke-width="2"/><rect x="4" y="10" width="16" height="12" rx="4" fill="currentColor"/></svg>'}</span><span class="stop-name">${s.name}</span><span class="stop-action">${progress.session?.level===i?'Resume':progress.stars[i]?'Replay':i===currentStop()?'Play next':unlocked(i)?'Play':'Locked'}</span><span class="stop-stars" aria-label="${progress.stars[i]} of 3 stars">${'★'.repeat(progress.stars[i])}${'☆'.repeat(3-progress.stars[i])}</span>`;button.setAttribute('aria-label',`${s.name}, ${progress.session?.level===i?'Resume, in progress':progress.stars[i]?'Replay, completed':i===currentStop()?'Play next':''}, ${progress.stars[i]} of 3 stars${!unlocked(i)?', locked':''}`);button.onclick=()=>brief(i);$('tourRoute').appendChild(button);});
  const all=progress.stars.every(Boolean),resume=progress.session&&unlocked(progress.session.level);
  $('tourPlay').textContent=resume?'▶  Resume show':all?'↻ Replay finale':'▶ Play next';
  $('tourStatus').textContent=resume?`${stages[progress.session.level].name} is waiting for your return.`:all?'Ten venues complete. Replay to improve your stars.':progress.stars.some(Boolean)?`${stages[next()].name} is unlocked. Your next crowd is waiting.`:'Every headline show starts with a first rehearsal.';
  $('tourPlay').onclick=()=>resume?resumeShow():brief(next());persist();
  if(typeof requestAnimationFrame==='function')requestAnimationFrame(centerCurrentStage);
 }
 function showTour(){if(busy)return;saveSession();finished=true;$('playScreen').hidden=true;$('tour').hidden=false;document.body.dataset.screen='tour';chapter=Math.floor(currentStop()/5);route();$('tourPlay').focus({preventScroll:true});}
 function brief(n){if(!unlocked(n))return;if(progress.session?.level===n){resumeShow();return;}selectedStop=n;loadout=[];updateLoadout();$('beginShow').textContent=progress.stars[n]?'Replay stage →':'Take the stage →';$('briefNumber').textContent=`TOUR STOP ${String(n+1).padStart(2,'0')}`;$('briefTitle').textContent=stages[n].name;$('briefStory').textContent=stories[n];$('briefIcon').className='token token-'+stages[n].type;$('briefGoal').textContent=`Collect ${stages[n].target} ${['stars','hearts','notes','beats','tickets','gems'][stages[n].type]}`;$('briefMoves').textContent=`${stages[n].moves} moves · no timer`;$('briefTip').textContent=tips[n%5];$('briefing').showModal();}
 function enter(){ $('tour').hidden=true;$('playScreen').hidden=false;document.body.dataset.screen='play';document.body.dataset.venue=String(level);$('feedback').textContent=stories[level];updateStats();$('backTour').focus(); }
 function launch(n){start(n);applyStartingBoosters(loadout);loadout=[];enter();saveSession();}
 function saveSession(){if(finished||!board.length||busy)return;progress.session={level,board:board.map(t=>t?{...t}:null),moves,score,collected,tools:{...toolStock}};persist();}
 function resumeShow(){const s=progress.session;const n=s?.level;if(!Number.isInteger(n)||n<0||n>=stages.length||!unlocked(n)){progress.session=null;route();return;}start(n);const valid=Array.isArray(s.board)&&s.board.length===64&&s.board.every((t,i)=>activeCell(i)?t&&Number.isInteger(t.type)&&t.type>=0&&t.type<6&&[null,'row','column','color'].includes(t.special):t===null)&&Number.isInteger(s.moves)&&s.moves>0&&s.moves<=stages[n].moves+3&&Number.isInteger(s.collected)&&s.collected>=0&&s.collected<stages[n].target&&Number.isInteger(s.score)&&s.score>=0;
  if(valid){board=s.board.map(t=>t?{...t}:null);moves=s.moves;score=s.score;collected=s.collected;toolStock=Object.fromEntries(['tap','shuffle','moves'].map(k=>[k,s.tools?Number(s.tools[k])===1?1:0:1]));if(matches().length||!possible()){fresh();}render();}enter();saveSession();}
 function finish(won){progress.session=null;const earned=won?(moves>=Math.ceil(stages[level].moves*.4)?3:moves>=Math.ceil(stages[level].moves*.15)?2:1):0;if(won){progress.stars[level]=Math.max(progress.stars[level],earned);progress.best[level]=Math.max(progress.best[level],score);}persist();$('resultEyebrow').textContent=won?'THE CROWD IS YOURS':'ONE MORE TAKE';$('resultTitle').textContent=won?(level===stages.length-1?'Your headline moment.':'You lit up the stage.'):'Your encore is waiting.';document.querySelector('.result-symbol').textContent=won?'★'.repeat(earned):'↻';$('resultText').textContent=won?`${score.toLocaleString()} points · ${earned} tour ${earned===1?'star':'stars'}. ${level===stages.length-1?'The whole tour is complete. Replay venues to improve your stars.':stages[level+1].name+' is now unlocked.'}`:`You collected ${Math.min(collected,stages[level].target)} of ${stages[level].target}. Try using four-piece matches to clear more of the board.`;$('continue').textContent=won?(level===stages.length-1?'See your tour →':'Next venue →'):'Try another take →';$('continue').onclick=()=>{$('result').close();if(won){showTour();if(level<stages.length-1)brief(level+1);}else launch(level);};$('resultTour').onclick=()=>{$('result').close();showTour();};$('result').showModal();}
 window.concertTour={finish,saveSession,update(){const pct=Math.min(100,Math.round(collected/stages[level].target*100));$('energyValue').textContent=pct+'%';document.body.style.setProperty('--energy',pct/100);$('backTour').disabled=busy;}};
 $('beginShow').onclick=()=>{$('briefing').close();launch(selectedStop);};$('cancelBrief').onclick=()=>$('briefing').close();$('backTour').onclick=showTour;
 function updateLoadout(){for(const key of ['lasers','bomb'])$('boost-'+key).setAttribute('aria-pressed',String(loadout.includes(key)));}
 for(const key of ['lasers','bomb'])$('boost-'+key).onclick=()=>{loadout=loadout.includes(key)?loadout.filter(x=>x!==key):[...loadout,key];updateLoadout();};
 $('chapterPrev').onclick=()=>{chapter=Math.max(0,chapter-1);route();};$('chapterNext').onclick=()=>{chapter=Math.min(Math.ceil(stages.length/5)-1,chapter+1);route();};
 function $(id){return document.getElementById(id);}
 document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();if(!busy){$('result').close();$('briefing').close();showTour();}});
 $('restart').onclick=()=>{if(!busy){start(level);enter();saveSession();}};
 if(typeof ResizeObserver==='function'){const observer=new ResizeObserver(()=>{if(typeof requestAnimationFrame==='function')requestAnimationFrame(centerCurrentStage);});observer.observe(document.querySelector('.world-map'));observer.observe($('tourRoute'));}
 finished=true;$('playScreen').hidden=true;document.body.dataset.screen='tour';chapter=Math.floor(currentStop()/5);route();
})();
